### ISSUE TITLE
HTML Formatting in calendar.rb

### ISSUE THREAD

**Issue by tjachimiak** [concerto/concerto-calendar#19] opened 2018-02-23 16:39 UTC
Concerto Version: 2.3.5
Concerto Calendar Version: 0.0.9

Marvin,
Thank you for a great calendar plugin for Concerto. I am attempting to figure out why the output is not displaying in the manner that I was hoping. I am using the LIST or HEADLINES format to display results in the right-side text area of the BlueSwoosh theme. It seems that the item name is not on its own line rather it is showing up right next to the event time. I am trying to get the event name on the first line (in bold or h1) then the date on the second line (h2 or bold p) then the time on the bottom line (h2 or bold p). Please, see the attached image which shows what the existing output is and how I would like to format it.

> The ical feed that I am using is: **https://www.havelocknc.us/calendar/?ical=1&month-feed**

![concerto-calendar-formatting](https://user-images.githubusercontent.com/36631400/36604249-2f669bfa-188b-11e8-9260-20f5dcd2e36d.jpg)

When looking at the file '**calendar.rb**' , I  found this code which I can't seem to isolate the item name to move it before the date. It is almost like the time and item name are inside the same field because it shows up like -- **5:30pm - 8:30 pmECAHF Gala**

*********************************************************************
      when '**headlines**' # 5 items per entry, titles only
        result.items.each_slice(5).with_index do |items, index|
          htmltext = HtmlText.new()
          htmltext.name = "#{result.name} (#{index+1})"
          htmltext.data = "<h1>#{result.name}</h1>#{items_to_html(items, day_format, time_format)}"
          contents << htmltext
        end
      when '**detailed**' # each item is a separate entry, title and description
        result.items.each_with_index do |item, index|
          htmltext = HtmlText.new()
          htmltext.name = "#{result.name} (#{index+1})"
          htmltext.data = item_to_html(item, day_format, time_format)
          contents << htmltext
        end
***********************************************************************
  def item_to_html(item, day_format, time_format)
    start_time = item.start_time.strftime(time_format)
    end_time = item.end_time.strftime(time_format) unless item.end_time.nil?

    html = []
    html << "<h1>#{item.name}</h1>"
    html << "<h2>#{item.start_time.strftime(day_format)}</h2>" 
    html << (end_time.nil? || start_time == end_time ? "<div class=\"cal-time\">#{start_time}</div>" : "<div class=\"cal-time\">#{start_time} - #{end_time}</div>")
    html << "<div class=\"cal-location\">#{item.location}</div>"
    html << "<p>#{item.description}</p>"
    return html.join("")
  end

  # display date (only when it changes) / times with title...
  **def items_to_html(items, day_format, time_format)
    html = []
    last_date = nil
    items.each do |item|
      # see if we need a date header
      if last_date != item.start_time.to_date
        if last_date.nil?
          # dont need to close list
        else
          html << "</dl>"
        end
        html << "<h2>#{item.start_time.strftime(day_format)}</h2>"
        html << "<dl>"
      end**
      # todo: end time should include date if different
      start_time = item.start_time.strftime(time_format)
      end_time = item.end_time.strftime(time_format) unless item.end_time.nil?

      html << (end_time.nil? || start_time == end_time ? "<dt>#{start_time}</dt>" : "<dt>#{start_time} - #{end_time}</dt>")
      # if the item we're evaluating isn't a DateTime, it's a full-day event
      html << (item.start_time.is_a?(DateTime) ? "" : "<dt>Time N/A</dt>")
      html << "<dd>#{item.name}</dd>"
      last_date = item.start_time.to_date
    end
    html << "</dl>" if !last_date.nil?
    return html.join("")
  end
*******************************************************************************

Thank you for any insight/help that you can give me.

Todd Jachimiak, Network Admin/Webmaster
City of Havelock, North Carolina
tjachimiak@havelocknc.us

**Comment by mjsamberg** [comment] 2018-02-28 18:16
Once thing I noticed is that in the Ruby source code, things are classed, in which case it would be pretty simple to format them. On the screen, nothing is classed...

**Comment by mjsamberg** [comment] 2018-02-28 19:06
@tjachimiak I was able to get a working solution. I replaced the items_to_html method as follows. Now each element is classable and I can use my screen CSS to control what it looks like:

```
def items_to_html(items, day_format, time_format)
    html = []
    last_date = nil
    items.each do |item|
      # see if we need a date header
      if last_date != item.start_time.to_date
        html << "<h2>#{item.start_time.strftime(day_format)}</h2>"
      end
      # todo: end time should include date if different
      start_time = item.start_time.strftime(time_format)
      end_time = item.end_time.strftime(time_format) unless item.end_time.nil?
      html << (end_time.nil? || start_time == end_time ? "<div class=\"event-time\"><div class=\"event-time-start\">#{start_time}</div></div>" : "<div class=\"event-time\"><div class=\"event-time-start\">#{start_time}</div><div class=\"event-time-sep\"> - </div><div class=\"event-time-end\">#{end_time}</div></div>")
      html << "<div class=\"event-title\">#{item.name}</div>"
      last_date = item.start_time.to_date
    end
    return html.join("")
  end
```

I'll do a pull request for this at some point.

**Comment by tjachimiak** [comment] 2018-02-28 19:11
Mark,

Thank you so much for tackling this for me. I wish that I was more versed in coding, but I know my limits. Haaa! Were you able to test with the live iCal link that I had in the post?
So, I should be able to replace the existing code with what you have below, yes?

**Comment by mjsamberg** [comment] 2018-02-28 19:45
I tested it with my own iCal link and it does work, I didn't try it with yours. You'll have to do some tweaking after you replace the code:
1) Regenerate the content for your calendars
2) Update your theme's CSS file with the following CSS:
```
.event-time-start, .event-time-sep, .event-time.end {
display: inline;
}
```
Style the rest of the things as you want to.

**Comment by tjachimiak** [comment] 2018-03-09 16:22
Hi Mark.

I did everything that you said but I wasn't sure where to put the CSS that you have below. I created a css file under  /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/concerto_calendar-0.0.9/app/assets/stylesheets/concerto_calendar in which application.css is supposed to include any css file in this folder. It is a little confusing where the CSS should be added too. In the Concerto admin site, the templates allow style only.
[cid:image004.jpg@01D3B798.DE76B570]

This talks about CSS but doesn't say where to update it: https://github.com/concerto/concerto/wiki/Templates

The output is still running the time next to the item-name:
[cid:image001.png@01D3B798.25F0DAD0]

I am so thankful that you have gotten me this far and so close to the way that we would like it formatted.

Todd

**Comment by mjsamberg** [comment] 2018-03-09 19:20
I attached the CSS file to my screen design.

**Comment by tjachimiak** [comment] 2018-03-09 19:22
Are you talking about this:
[cid:image001.png@01D3B7B2.10F5C400]

**Comment by mjsamberg** [comment] 2018-03-09 19:28
I can't see the image.

**Comment by tjachimiak** [comment] 2018-03-09 19:30
Sorry that the image won't come through. It was just a snippet of the Template Editor screen where you can add a custom CSS file using the 'choose file' button.

I uploaded the custom CSS file via the Template Editor screen. I don't think it is working even after restarting the web server. Maybe you can see this screen,

http://concerto.havelocknc.us/frontend/3?preview=true

**Comment by mjsamberg** [comment] 2018-03-09 19:31
I can't - it says that the screen requires authentication.

**Comment by tjachimiak** [comment] 2018-03-09 19:34
I can add you on as a user. Would that help? I just need a email address for your log in.

Our conversation isn't posting to Github is it? Cause I don't want your email going there. Email me directly @ tjachimiak@havelocknc.us

**Comment by mfrederickson** [comment] 2018-09-12 05:31
@tjachimiak did you ever get this working to your satisfaction?  I'm working on two other view types... one is a list of days each with a list of events, and the other is a user-specified templated item.

![selection_331](https://user-images.githubusercontent.com/473165/45404073-eeabd680-b609-11e8-867a-0da84506f861.png)


![image](https://user-images.githubusercontent.com/473165/45403679-24e85680-b608-11e8-9626-9fe681535f89.png)

Example CSS file for that last screenshot:
```
.cal-custom-list {
  text-align: center;
}

.event-title {
  font-weight: bold;
  font-size: 1.2em;
}

.event-date {
  color: lemonchiffon;
}

.event {
  margin-bottom: 1em;
}

.event-location {
  font-size: .8em;
  color: #aaa;
  margin-top: .2em;
}

.event-description {
  font-size: .6em;
  font-style: italic;
}
```

**Comment by tjachimiak** [comment] 2018-09-12 06:10
Yes. There were a few lines of code that needed to be altered. It looks so much better now.

I am very excited that you are continuing on this project. I would like to be part of your testing group when you are ready.


Todd Jachimiak
Network Admin/Webmaster
City of Havelock NC
tjachimiak@havelocknc.us
252-463-7190


-------- Original message --------

**Comment by mfrederickson** [comment] 2018-09-13 00:54
That would be great.  I welcome anyone that would like to test this 0.1.0 release.  You can edit your calendar plugin source to be `Git Repository` and then specify the source url as `https://github.com/mfrederickson/concerto-calendar.git` and when you are done testing, you can always revert it back (after you delete the content that uses the new layouts).

It would be nice if you could `force update` your existing calendar content and see how it differs (it shouldn't).  And then check out the two new output format styles and see how they work for you.  You'll most likely want to add some CSS styling to whichever templates you are using to make the calendar entries look nice-- see the [README.md](https://github.com/mfrederickson/concerto-calendar/blob/master/README.md) for more info.

Once we fix anything you find I'll see about getting this merged upstream and the update published to rubygems.

# Major Changes
* fields are now html_escaped if that causes a problem for anyone let me know
* iCal *recurring events* show up now
* two new layouts are offered (see the readme mentioned above)
* css classes have been added (again, see the readme)
* the hardcoded "Time N/A" has been removed from one of the layouts

Thanks.  I appreciate everyone's time and help.

**Comment by jamodamo** [comment] 2018-12-14 11:46
Thank you for your work on this plugin! Concerto is a really wonderful signage system. I would love to be able to test the calendar plugin update as we use recurring events in iCal and would love to make use of the new layouts, but I have tried to add the plugin using your Git reference, but it's not updating past 0.9.0. Any assistance with this would be appreciated.

**Comment by mzocher** [comment] 2019-01-30 04:11
Thank you @mfrederickson for your fixes and for the formatting options!  I did run into a bug with a specific type of reoccurring event.  The event below caused the browser to lock up for 30-60 seconds, then I received the error 

`1 error prevented this calendar from being saved:  Could not fetch calendar - Unsupported time object passed: [Thu, 08 Nov 2018 11:00:00 -0800, Thu, 15 Nov 2018 11:00:00 -0800, Thu, 24 Jan 2019 11:00:00 -0800]`



Here's the iCal meeting entry for the reoccurring event:
`BEGIN:VEVENT
RRULE:FREQ=WEEKLY;UNTIL=20190131T190000Z;INTERVAL=1;BYDAY=TH;WKST=SU
EXDATE;TZID=Pacific Standard Time:20181108T110000,20181115T110000,20190124T
 110000
UID:040000008200E00074C5B7101A82E00800000000E0005BB27F9ED301000000000000000
 0100000009E8BC938DBA1C9449CA29297009F6416
SUMMARY:Mark/Dave check-in
DTSTART;TZID=Pacific Standard Time:20181101T110000
DTEND;TZID=Pacific Standard Time:20181101T113000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20190129T040409Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Dave's office
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT`

**Comment by tjachimiak** [comment] 2019-03-07 20:08
Marvin,

I have been forced to create a new Concerto server on a new VM (hyper-v) since we are doing away with the older Xen system. I installed Debian Stretch and got Concerto 2.3.6 running. All was great and I got everything re-created from the other install (screens, content, feeds, etc).

I decided to implement your new concerto-calendar v0.1.0 and as soon as I added via plugins (from github), concerto crashed with the "We're Sorry, but something went wrong." Phusion Passenger page.

I cannot find out how to remove or disable your plugin from the file system or shell. I think that I named the gem 'concerto-calendar2' not realizing that this may have broke something. I left the existing and working concerto_calendar enabled so that I could go back and forth if needed.

Not sure what to do, bro. I tried gem uninstall and gem cleanup with no luck. Hope you can give me some help getting these removed so that the site works again.

See the attached error log which looks like there could be a bundler version conflict.

Thanks,
Todd

[HavelockSeal150px]


Todd 'Jack' Jachimiak, Network Administrator/Webmaster

(Office) 252-463-7190 (Mobile) 336-430-0209

PO BOX 368
Havelock, NC 28532
tjachimiak@havelocknc.us<mailto:tjachimiak@havelocknc.us>


The information contained within the referenced, linked, or directed email communication is intended to be a confidential communication between the original sender and recipient, and is to be treated as confidential. All works, ideas, or copy within are copyrighted by the City of Havelock, NC and are not to be used in any manner other by which they were intended by the City of Havelock, NC. If you believe you have received this or any other email in error, please contact tjachimiak@havelocknc.us<mailto:tjachimiak@havelocknc.us> immediately.

**Comment by tjachimiak** [comment] 2019-03-07 20:34
A reinstall of concerto-full solved the issue and let me remove the plugin. I am scared to try it again.

Thanks,
Todd

[HavelockSeal150px]


Todd 'Jack' Jachimiak, Network Administrator/Webmaster

(Office) 252-463-7190 (Mobile) 336-430-0209

PO BOX 368
Havelock, NC 28532
tjachimiak@havelocknc.us<mailto:tjachimiak@havelocknc.us>


The information contained within the referenced, linked, or directed email communication is intended to be a confidential communication between the original sender and recipient, and is to be treated as confidential. All works, ideas, or copy within are copyrighted by the City of Havelock, NC and are not to be used in any manner other by which they were intended by the City of Havelock, NC. If you believe you have received this or any other email in error, please contact tjachimiak@havelocknc.us<mailto:tjachimiak@havelocknc.us> immediately.

**Closed as completed** 2020-08-07 20:27 UTC
